# Generated by Django 5.1.15 on 2026-09-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_riyadhassalihin_audio_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=32, unique=True, verbose_name='ID видео на YouTube')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка на видео')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации на YouTube')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда сайт заметил видео')),
            ],
            options={
                'verbose_name': 'Новое видео (YouTube)',
                'verbose_name_plural': 'Новые видео (YouTube)',
                'ordering': ['-published_at'],
            },
        ),
    ]
